name: CI Pipeline

on:
  push:
    branches:
      - main
      - staging
      - production
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Code Quality & Build Validation
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-cache-${{ runner.os }}-

      - name: Run ESLint
        run: npm run lint

      - name: Type check only (PR/Main)
        if: github.event_name == 'pull_request' || github.ref_name == 'main'
        run: npx tsc --noEmit

      - name: Cache Amplify Outputs
        if: github.event_name == 'push' && (github.ref_name == 'staging' || github.ref_name == 'production')
        uses: actions/cache@v4
        with:
          path: amplify_outputs.json
          key: amplify-outputs-${{ github.ref_name }}-${{ hashFiles('amplify/**') }}
          restore-keys: |
            amplify-outputs-${{ github.ref_name }}-

      - name: Configure AWS Credentials
        if: github.event_name == 'push' && (github.ref_name == 'staging' || github.ref_name == 'production')
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-southeast-1

      - name: Generate Amplify Outputs
        if: github.event_name == 'push' && (github.ref_name == 'staging' || github.ref_name == 'production')
        run: |
          if [ ! -f amplify_outputs.json ]; then
            echo "Generating fresh Amplify outputs..."
            npx ampx generate outputs --branch ${{ github.ref_name }} --app-id d39qthns8fi2t1 --out-dir ./
          else
            echo "Using cached Amplify outputs"
          fi

      - name: Build for deployment
        if: github.event_name == 'push' && (github.ref_name == 'staging' || github.ref_name == 'production')
        run: npm run build

      - name: Upload build artifacts
        if: github.event_name == 'push' && (github.ref_name == 'staging' || github.ref_name == 'production')
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.ref_name }}
          path: dist/ # or your build output directory
          retention-days: 7
