name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
      - production

  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build, Test & Deploy Workflow
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Configure AWS Credentials (Staging/Production)
        if: github.event_name == 'push' && (github.ref_name == 'staging' || github.ref_name == 'production')
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          aws-access-key-id: ${{ secrets.USER_AWS_KEY }}
          aws-secret-access-key: ${{ secrets.USER_AWS_SECRET }}
          aws-region: ap-southeast-1

      - name: Generate Amplify Outputs (Staging/Production)
        if: github.event_name == 'push' && (github.ref_name == 'staging' || github.ref_name == 'production')
        run: npx ampx generate outputs --branch ${{ github.ref_name }} --app-id ddj8wod0nlg9s --out-dir ./

      - name: Build application (Staging/Production)
        if: github.event_name == 'push' && (github.ref_name == 'staging' || github.ref_name == 'production')
        run: npm run build

      - name: Deploy to Staging
        if: github.event_name == 'push' && github.ref_name == 'staging'
        run: |
          echo "Starting deployment to Staging..."

      - name: Deploy to Production
        if: github.event_name == 'push' && github.ref_name == 'production'
        run: |
          echo "Starting deployment to Production..."
