name: TaytThreads CI
on:
  pull_request:
    types: ["opened"]
permissions:
  pull-requests: write
jobs:
  build:
    name: Run Build Application
    runs-on: ubuntu-latest
    steps:
      - run: bun run build
      - run: bun run lint
